---

- name: Include NAT setup task
  ansible.builtin.include_tasks:
    file: vmbr0_setup.yml

- name: Include NAT setup task
  ansible.builtin.include_tasks:
    file: vmbr1_setup.yml

- name: Include Proxmox installation task for Noble Numbat
  ansible.builtin.include_tasks:
    file: noblenumbat_proxmox_install.yml
  when: ansible_facts['distribution_release'] == "noble"

...
